# fly.toml app configuration file generated for tic-tac-toe-game on 2024-10-15T17:48:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tic-tac-toe-game'
primary_region = 'lhr'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '20'
    PHP_VERSION = '8.3'

[env]
  APP_NAME='Tic Tac Toe'
  APP_ENV = 'production'
  CACHE_STORE = 'redis'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'redis'
  REVERB_APP_ID = '674584'
  REVERB_APP_KEY = 'u0q5ycbcqcmmbapz54vz'
  REVERB_SERVER_HOST = 'https://reverb-server.fly.dev/'
  REVERB_PORT=8080
  VITE_REVERB_APP_KEY='${REVERB_APP_KEY}'
  VITE_REVERB_HOST='${REVERB_SERVER_HOST}'
  VITE_REVERB_PORT='${REVERB_PORT}'
  VITE_REVERB_SCHEME='${REVERB_SCHEME}'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source='storage_vol'
  destination='/var/www/html/storage'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
