# fly.toml app configuration file generated for tic-tac-toe-game on 2024-10-15T17:48:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tic-tac-toe-game'
primary_region = 'lhr'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '20'
    PHP_VERSION = '8.3'

[env]
  APP_NAME='Tic Tac Toe'
  APP_ENV = 'production'
  CACHE_STORE = 'redis'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'redis'
  REVERB_SERVER_PORT = '6060'
  REVERB_HOST = 'https://tic-tac-toe-game.fly.dev/'
  REVERB_APP_ID = '991707'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source='storage_vol'
  destination='/var/www/html/storage'

[[services]]
  internal_port = 6060
  processes = ["reverb"]

[processes]
  app = ""
  reverb = "php artisan reverb:start"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
